name: Robust Release

# 觸發條件：當創建tag時執行
on:
  push:
    tags:
      - 'v*'  # 匹配所有以v開頭的tag，如 v1.0.0

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    # 步驟1: 檢出代碼
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # 獲取完整的git歷史
    
    # 步驟2: 設置Node.js環境
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    # 步驟3: 安裝依賴
    - name: Install dependencies
      run: npm ci
    
    # 步驟4: 構建項目
    - name: Build project
      run: npm run build
    
    # 步驟5: 配置Git用戶信息
    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
    
    # 步驟6: 準備release分支
    - name: Prepare release branch
      run: |
        # 獲取當前tag名稱
        TAG_NAME=${GITHUB_REF#refs/tags/}
        echo "Processing tag: $TAG_NAME"
        
        # 檢查release分支是否存在
        if git show-ref --verify --quiet refs/remotes/origin/release; then
          echo "Release branch exists, checking it out"
          git fetch origin release
          git checkout -B release origin/release
        else
          echo "Release branch does not exist, creating it"
          git checkout --orphan release
        fi
        
        # 清空工作目錄（忽略錯誤）
        find . -maxdepth 1 -not -name '.git' -not -name '.' -exec rm -rf {} + 2>/dev/null || true
    
    # 步驟7: 複製構建文件
    - name: Copy build files
      run: |
        TAG_NAME=${GITHUB_REF#refs/tags/}
        
        # 從tag複製構建文件
        git checkout $TAG_NAME -- dist/
        git checkout $TAG_NAME -- index.html
        git checkout $TAG_NAME -- package.json
        git checkout $TAG_NAME -- README.md
        
        # 確保dist目錄存在
        if [ ! -d "dist" ]; then
          echo "Error: dist directory not found after build"
          exit 1
        fi
        
        echo "Build files copied successfully"
        ls -la
    
    # 步驟8: 創建發布說明
    - name: Create release notes
      run: |
        TAG_NAME=${GITHUB_REF#refs/tags/}
        cat > RELEASE_NOTES.md << EOF
        # Release $TAG_NAME
        
        **發布時間**: $(date -u '+%Y-%m-%d %H:%M:%S UTC')
        
        **Tag**: $TAG_NAME
        
        **構建信息**:
        - 構建時間: $(date -u '+%Y-%m-%d %H:%M:%S UTC')
        - 構建環境: GitHub Actions (Ubuntu Latest)
        - Node.js版本: $(node --version)
        - NPM版本: $(npm --version)
        
        **文件列表**:
        \`\`\`
        $(find dist -type f | head -20)
        \`\`\`
        
        ## 部署說明
        此版本已準備好部署到生產環境。
        EOF
    
    # 步驟9: 提交更改
    - name: Commit changes
      run: |
        TAG_NAME=${GITHUB_REF#refs/tags/}
        
        # 添加所有文件
        git add .
        
        # 提交
        git commit -m "Release $TAG_NAME

        - 構建時間: $(date -u '+%Y-%m-%d %H:%M:%S UTC')
        - 基於tag: $TAG_NAME
        - 自動構建並部署到release分支"
    
    # 步驟10: 推送到release分支
    - name: Push to release branch
      run: |
        echo "Pushing to release branch..."
        git push origin release
    
    # 步驟11: 輸出構建信息
    - name: Build summary
      run: |
        TAG_NAME=${GITHUB_REF#refs/tags/}
        echo "🎉 構建完成！"
        echo "📦 Tag: $TAG_NAME"
        echo "🌿 Release分支: release"
        echo "📁 構建文件: dist/"
        echo "📋 發布說明: RELEASE_NOTES.md"
        echo ""
        echo "構建文件列表:"
        find dist -type f | head -10
