name: Simple Release

# 觸發條件：當創建tag時執行
on:
  push:
    tags:
      - 'v*'  # 匹配所有以v開頭的tag

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    # 檢出代碼
    - name: Checkout
      uses: actions/checkout@v4
    
    # 設置Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    # 安裝依賴並構建
    - name: Install and Build
      run: |
        npm ci
        npm run build
    
    # 配置Git
    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
    
    # 切換到release分支
    - name: Switch to release branch
      run: |
        # 嘗試切換到現有的release分支，如果不存在則創建新的orphan分支
        if git show-ref --verify --quiet refs/remotes/origin/release; then
          echo "Switching to existing release branch"
          git checkout -B release origin/release
          git rm -rf . 2>/dev/null || true
        else
          echo "Creating new orphan release branch"
          git checkout --orphan release
          git rm -rf . 2>/dev/null || true
        fi
        
        # 複製構建文件（dist目錄已在當前工作空間中）
        git checkout ${GITHUB_REF#refs/tags/} -- index.html package.json README.md
    
    # 提交並推送
    - name: Commit and Push
      run: |
        git add .
        git commit -m "Release ${GITHUB_REF#refs/tags/} - $(date)"
        git push origin release
